// src/app/components/ui/TimePicker.tsx
"use client";

import React, {useState, useRef, useEffect} from "react";
import { DateTime } from "luxon";
import Image from "next/image";

interface Props {
    onChangedDate: (date: DateTime) => void;
}

const TimePicker: React.FC<Props> = ({ onChangedDate }) => {
    const [selectedDate, setSelectedDate] = useState<DateTime>(() =>
        DateTime.now().set({ second: 0, millisecond: 0 })
    );

    const [showPicker, setShowPicker] = useState(false); // Toggle for calendar
    const pickerRef = useRef(null);

    const inputTimeout = useRef(null); // Ref for input timeout
    const buffer = useRef({ hours: "", minutes: "" }); // Buffer for input

    // Helper functions
    const prevMonth = () => setSelectedDate(selectedDate.minus({ months: 1 }));
    const nextMonth = () => setSelectedDate(selectedDate.plus({ months: 1 }));

    const renderCalendarDays = () => {
        const startDate = selectedDate.startOf("month").startOf("week");
        const endDate = selectedDate.endOf("month").endOf("week");

        let days = [];
        let day = startDate;

        while (day <= endDate) {
            days.push(day);
            day = day.plus({ days: 1 });
        }

        return days.map((day) => (
            <div
                key={day}
                className={`p-2 text-center
                    ${day.hasSame(selectedDate, "month") ? "" : "text-gray-400"}
                    ${day.hasSame(selectedDate, "day")
                        ? "bg-aqua text-black font-bold rounded-full"
                        : ""
                }`}
                onClick={() => setSelectedDate((prev) =>
                    day.set({ hour: prev.hour, minute: prev.minute })
                )}
            >
                {day.day}
            </div>
        ));
    };

    const adjustTimeByMinutes = (amount: number) => {
        setSelectedDate((prev) => prev.plus({ minutes: amount }));
    };

    useEffect(() => {
        const handleClickOutside = (e: MouseEvent) => {
            if (pickerRef.current && !pickerRef.current.contains(e.target)) {
                setShowPicker(false);
            }
        }

        if (selectedDate) onChangedDate(selectedDate);

        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, [selectedDate]);

    const handleKeyPress = (e) => {
        const part = e.target.dataset.part;
        if (!part || (part !== "minutes" || part !== "hours"))
        if (!/^\d+$/.test(e.key)) return;

        clearTimeout(inputTimeout.current);
        buffer.current[part] += e.key;

        if (buffer.current[part].length === 2) {
            // validate if two digits are entered
            const maxValue = part === "hours" ? 23 : 59;
            const validatedValue = Math.min(parseInt(buffer.current[part], 10), maxValue);

            setSelectedDate((prev) =>
                part === "hours"
                    ? prev.set({ hour: validatedValue })
                    : prev.set({ minute: validatedValue })
            );

            // reset buffer
            buffer.current[part] = "";
        } else {
            setSelectedDate((prev) =>
                part === "hours"
                    ? prev.set({ hour: parseInt(e.key, 10) || 0 })
                    : prev.set({ minute: parseInt(e.key, 10) || 0 })
            );

            inputTimeout.current = setTimeout(() => buffer.current[part] = "", 500);
        }
    };

    return (
        <div className="relative rounded-xl text">
            {/* Input Field */}
            <div className="flex flex-row space-x-2">
                <div className={"flex flex-row items-center space-x-2 md:space-x-4 p-2 grow bg-lightgray rounded"}
                     onClick={() => setShowPicker(true)}
                >
                    <Image className={"p-1 md:h-[35px] md:w-[35px]"} width={25} height={25} src={"/ui/calendar.svg"} alt={"CALENDAR"} />
                    <span
                        className={"w-full text-base md:text-2xl bg-lightgray text-text cursor-pointer focus:outline-none"}
                    >
                        {selectedDate.toFormat("dd.MM.yyyy - HH:mm")}
                    </span>
                </div>
                <button className={"w-fit py-2 px-3 md:px-6 bg-white rounded font-bold"} onClick={() => setSelectedDate(DateTime.now().set({ second: 0, millisecond: 0 }))}>Now</button>
            </div>

            {/* Calendar Picker */}
            {showPicker && (
                <div
                    ref={pickerRef}
                    className="absolute top-1/2 left-1/2 mt-8 transform -translate-x-1/2 p-4 w-80 md:top-full md:left-auto md:transform-none md:mt-2 md:w-auto z-10 shadow-lg rounded bg-lightgray text-white"
                >
                    {/* header */}
                    <div className="flex justify-between items-center mb-4">
                        <button onClick={prevMonth}>&lt; {selectedDate.minus({ months: 1 }).toFormat("MMM")}</button>
                        <div className={"font-bold"}>{selectedDate.toFormat("MMMM yyyy")}</div>
                        <button onClick={nextMonth}>{selectedDate.plus({ months: 1 }).toFormat("MMM")} &gt;</button>
                    </div>

                    {/* calendar grid */}
                    <div className="grid grid-cols-7 gap-1 text-sm">
                        {["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"].map((day) => (
                            <div key={day} className="font-bold text-center">
                                {day}
                            </div>
                        ))}
                        {renderCalendarDays()}
                    </div>

                    {/* time inputs */}
                    <div className="mt-4 flex items-center justify-between font-bold space-x-2">
                        <button
                            className="bg-aqua text-black px-4 md:px-3 py-1 rounded"
                            onClick={() => adjustTimeByMinutes(-15)}
                        >
                            -
                        </button>

                        <div className="flex items-center space-x-2">
                            <input
                                type="text"
                                name="hours"
                                data-part="hours"
                                value={String(selectedDate.hour).padStart(2, "0")}
                                onKeyDown={handleKeyPress}
                                maxLength={2}
                                readOnly={true}
                                className="w-full border rounded text-center text-xl bg-lightgray text-white border-none focus:outline-none"
                            />
                            <span>:</span>
                            <input
                                type="text"
                                name="minutes"
                                data-part="minutes"
                                value={String(selectedDate.minute).padStart(2, "0")}
                                onKeyDown={handleKeyPress}
                                maxLength={2}
                                readOnly={true}
                                className="w-full border rounded text-center text-xl bg-lightgray text-white border-none focus:outline-none"
                            />
                        </div>

                        <button
                            className="bg-aqua text-black px-4 md:px-3 py-1 rounded"
                            onClick={() => adjustTimeByMinutes(15)}
                        >
                            +
                        </button>
                    </div>

                    {/* select button */}
                    <button
                        className="mt-4 w-full bg-aqua font-bold text-black py-2 rounded"
                        onClick={() => {
                            setShowPicker(false);
                            onChangedDate(selectedDate);
                        }}
                    >
                        Select
                    </button>
                </div>
            )}
        </div>
    );
};

export default TimePicker;

// frontend/src/components/ui/controls/TimePicker.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { DateTime } from "luxon";
	import CalendarDays from "lucide-svelte/icons/calendar-days";

	let { selectedDate = $bindable(DateTime.now().set({ second: 0, millisecond: 0 })) } = $props();

	let isOpen: boolean = $state(false);
	let inputElement: HTMLDivElement;

	let inputTimeout: number;
	let buffer = { current: { hours: "", minutes: "" } };

	function clickOutside(event: MouseEvent) {
		if (inputElement.contains(event.target as Node)) return;
		isOpen = false;
	}

	onMount(() => {
		document.addEventListener("click", clickOutside);
		return () => document.removeEventListener("click", clickOutside);
	});

	const getDays = (): DateTime[] => {
		const startDate = selectedDate.startOf("month").startOf("week");
		const endDate = selectedDate.endOf("month").endOf("week");

		let days: DateTime[] = [];
		let day = startDate;

		while (day <= endDate) {
			days.push(day);
			day = day.plus({ days: 1 });
		}

		return days;
	};

	const adjustTimeByMinutes = (amount: number) => {
		selectedDate = selectedDate.plus({ minutes: amount });
	};

	const handleKeyPress = (e: KeyboardEvent) => {
		const part = (e.target as HTMLInputElement).dataset.part;
		if (!part || (part !== "minutes" && part !== "hours")) return;
		if (!/^\d+$/.test(e.key)) return;

		clearTimeout(inputTimeout);
		buffer.current[part] += e.key;

		if (buffer.current[part].length === 2) {
			// validate if two digits are entered
			const maxValue = part === "hours" ? 23 : 59;
			const validatedValue = Math.min(parseInt(buffer.current[part], 10), maxValue);

			selectedDate =
				part === "hours" ? selectedDate.set({ hour: validatedValue }) : selectedDate.set({ minute: validatedValue });

			// reset buffer
			buffer.current[part] = "";
		} else {
			selectedDate =
				part === "hours"
					? selectedDate.set({ hour: parseInt(e.key, 10) || 0 })
					: selectedDate.set({ minute: parseInt(e.key, 10) || 0 });

			inputTimeout = setTimeout(() => (buffer.current[part] = ""), 500);
		}
	};
</script>

<div bind:this={inputElement} class="relative w-fit">
	<button
		type="button"
		class:ring-2={isOpen}
		class:ring-accent={isOpen}
		class="hover:ring-accent flex cursor-pointer flex-row items-center gap-x-2 rounded-md p-0.5 text-center hover:ring-2 md:p-2 md:text-2xl"
		onclick={() => (isOpen = true)}
	>
		<CalendarDays />
		<span>{selectedDate.toFormat("dd.MM.yyyy - HH:mm")}</span>
	</button>

	{#if isOpen}
		<div
			class="bg-primary absolute top-1/2 left-1/2 z-10 mt-8 w-80 -translate-x-1/4 transform rounded-sm p-4 shadow-lg md:top-full md:left-auto md:mt-2 md:w-128 md:transform-none"
		>
			<!-- header -->
			<div class="mb-4 flex items-center justify-between">
				<button onclick={() => (selectedDate = selectedDate.minus({ months: 1 }))}>
					&lt; {selectedDate.minus({ months: 1 }).toFormat("MMM")}</button
				>
				<div class={"font-bold"}>{selectedDate.toFormat("MMMM yyyy")}</div>
				<button onclick={() => (selectedDate = selectedDate.plus({ months: 1 }))}
					>{selectedDate.plus({ months: 1 }).toFormat("MMM")}
					&gt;
				</button>
			</div>

			<!-- calendar grid -->
			<div class="grid grid-cols-7 gap-1 text-sm">
				{#each ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"] as day}
					<div class="text-center font-bold">
						{day}
					</div>
				{/each}

				{#each getDays() as day}
					<button
						class="p-2 text-center {day.hasSame(selectedDate, 'month') ? '' : 'text-gray-400'} {day.hasSame(
							selectedDate,
							'day'
						)
							? 'bg-accent rounded-md font-bold text-black'
							: ''}"
						onclick={() => (selectedDate = day.set({ hour: selectedDate.hour, minute: selectedDate.minute }))}
					>
						{day.day}
					</button>
				{/each}
			</div>

			<!-- time inputs -->
			<div class="mt-4 flex items-center justify-between space-x-2 font-bold">
				<button class="bg-accent rounded-sm px-4 py-1 text-black md:px-3" onclick={() => adjustTimeByMinutes(-15)}>
					-
				</button>

				<div class="flex items-center space-x-2">
					<input
						type="text"
						name="hours"
						data-part="hours"
						value={String(selectedDate.hour).padStart(2, "0")}
						onkeydown={handleKeyPress}
						maxLength={2}
						readOnly={true}
						class="text-text w-full rounded-sm border border-none bg-transparent text-center text-xl focus:outline-hidden"
					/>
					<span>:</span>
					<input
						type="text"
						name="minutes"
						data-part="minutes"
						value={String(selectedDate.minute).padStart(2, "0")}
						onkeydown={handleKeyPress}
						maxLength={2}
						readOnly={true}
						class="text-text w-full rounded-sm border border-none bg-transparent text-center text-xl focus:outline-hidden"
					/>
				</div>

				<button class="bg-accent rounded-sm px-4 py-1 text-black md:px-3" onclick={() => adjustTimeByMinutes(15)}>
					+
				</button>
			</div>

			<!-- select button -->
			<button class="bg-accent mt-4 w-full rounded-sm py-2 font-bold text-black" onclick={() => (isOpen = false)}>
				Select
			</button>
		</div>
	{/if}
</div>
