// frontend/src/components/ui/controls/StationSearch.svelte
<script lang="ts">
	import type { Station } from "$models/station";
	import { onMount, type Snippet } from "svelte";
	import { env } from "$env/dynamic/public";

	let {
		station = $bindable(undefined),
		placeholder = "Search for a station",
		children
	}: {
		station?: Station;
		placeholder: string;
		children: Snippet;
	} = $props();

	$effect(() => {
		if (!station) return;
		inputElement.value = station.name;
	});

	let open = $state<boolean>(false);
	let selectedIndex = $state<number>(-1);
	let stations: Station[] = $state([]);
	let inputElement: HTMLInputElement;
	const clickOutside = (event: MouseEvent) => {
		if (inputElement && inputElement.contains(event.target as Node)) return;
		open = false;
		selectedIndex = -1;
	};

	const searchStations = async (query: string) => {
		const searchParams = new URLSearchParams({ query }).toString();

		const response = await fetch(`${env.PUBLIC_BACKEND_BASE_URL}/api/v1/stations?${searchParams}`, { method: "GET" });
		if (!response.ok) return;

		const jsonData = await response.json();
		if (!Array.isArray(jsonData)) return;

		stations = jsonData as Station[];
		open = stations.length > 0;
	};

	const selectStation = (index: number) => {
		station = stations[index];
		inputElement.value = station?.name ?? "";
		open = false;
		selectedIndex = -1;
	};

	let debounce: number;
	const handleInput = () => {
		if (!inputElement) return;
		const value = inputElement.value;

		if (value.length === 0) {
			station = undefined;
			return;
		}

		if (!station || value !== station?.name) {
			clearTimeout(debounce);
			debounce = setTimeout(() => {
				if (value) {
					searchStations(value);
				} else {
					open = false;
				}
			}, 500);
		}
	};

	const handleKeyInput = (event: KeyboardEvent) => {
		if (!open || inputElement.value.length === 0) return;

		switch (event.key) {
			case "ArrowDown":
			case "Tab":
				event.preventDefault();
				selectedIndex = selectedIndex === stations.length - 1 ? 0 : selectedIndex + 1;
				break;
			case "ArrowUp":
				event.preventDefault();
				selectedIndex = selectedIndex === 0 ? stations.length - 1 : selectedIndex - 1;
				break;
			case "Enter":
				if (selectedIndex < 0 || selectedIndex > stations.length) return;
				selectStation(selectedIndex);
				break;
			case "Escape":
				open = false;
				break;
			default:
				break;
		}
	};

	onMount(() => {
		document.addEventListener("click", clickOutside);
		return () => document.removeEventListener("click", clickOutside);
	});
</script>

<div class="text-text placeholder:text-text relative flex w-full flex-col">
	<div
		class="bg-primary-dark focus-within:ring-accent flex flex-row items-center gap-x-1 rounded-2xl px-2 font-medium focus-within:ring-2 md:text-2xl"
	>
		{@render children()}
		<input
			bind:this={inputElement}
			type="text"
			class="bg-primary-dark w-full border-none p-2 outline-hidden"
			{placeholder}
			onclick={() => (open = true)}
			oninput={handleInput}
			onkeydown={handleKeyInput}
		/>
	</div>

	{#if open && stations.length > 0}
		<div
			class="border-text bg-primary-dark absolute top-full left-0 z-50 mt-1 flex h-fit max-w-96 flex-col rounded-lg border p-2"
		>
			{#each stations as station, index (station)}
				<button
					tabindex="0"
					onclick={() => selectStation(index)}
					onfocus={() => (selectedIndex = index)}
					class:bg-secondary={selectedIndex === index}
					class="w-full cursor-pointer rounded-md p-1 text-left"
				>
					{station?.name}
				</button>
			{/each}
		</div>
	{/if}
</div>

<style lang="postcss">
	::placeholder {
		color: var(--text);
		opacity: 0.75;
	}

	::-webkit-input-placeholder {
		color: var(--text);
	}

	::-moz-placeholder {
		color: var(--text);
		opacity: 0.75;
	}

	:-ms-input-placeholder {
		color: var(--text);
	}
</style>

// src/app/components/ui/StationSearch.tsx
import { Station } from "@/app/lib/objects";
import Image from "next/image";
import React, { useEffect, useRef, useState } from "react";

interface Props {
    onSelectStation: (station: Station) => void;
}

const StationSearch: React.FC<Props> = ({ onSelectStation }) => {
    const [query, setQuery] = useState<Station[]>([]);
    const [focusedQuery, setFocusedQuery] = useState<number | null>(null);

    const [isOpen, setIsOpen] = useState<boolean>(false);
    const [manualClose, setManualClose] = useState<boolean>(false); // tracks if dropdown was manually closed

    const [inputValue, setInputValue] = useState<string>("");

    const dropdownRef = useRef<HTMLDivElement>(null);

    const timeoutRef = useRef<NodeJS.Timeout | null>(null);

    useEffect(() => {
        if (!manualClose && inputValue.trim() !== "") setIsOpen(true);
    }, [inputValue]);

    // close dropdown when clicking outside
    useEffect(() => {
        const handleClickOutside = (event: MouseEvent) => {
            if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) setIsOpen(false);
        };

        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, []);

    const searchStations = async (query: string) => {
        const response = await fetch(`/api/v1/station`, {
            method: "POST",
            body: JSON.stringify({ query }),
        });
        if (!response.ok) return;

        const data = await response.json();
        if (!data.entries || data.entries.length === 0) return;

        const filtered: Station[] = data.entries
            .filter((location: any) => location.evaNr && location.name)
            .map((location: any) => location as Station);

        setQuery(filtered);
        setFocusedQuery(null);
    };

    const handleInputChange = (value: string) => {
        setInputValue(value);
        setManualClose(false);

        if (timeoutRef.current) clearTimeout(timeoutRef.current);
        timeoutRef.current = setTimeout(() => searchStations(value), 500);
    };

    const handleKeyInput = (e: React.KeyboardEvent<HTMLDivElement>) => {
        if (!isOpen || query.length === 0) return;

        switch (e.key) {
            case "ArrowDown":
            case "Tab":
                e.preventDefault();
                setFocusedQuery((prev) => (prev === null || prev === query.length - 1 ? 0 : prev + 1));
                break;
            case "ArrowUp":
                e.preventDefault();
                setFocusedQuery((prev) => (prev === null || prev === 0 ? query.length - 1 : prev - 1));
                break;
            case "Enter":
                e.preventDefault();
                if (focusedQuery !== null && query[focusedQuery]) selectStation(query[focusedQuery]);
                break;
            default:
                break;
        }
    };

    const selectStation = (station: Station) => {
        onSelectStation(station); // notify parent about station update
        setInputValue(station.name);
        setIsOpen(false); // close dropdown immediately
        setManualClose(true); // prevent reopening
    };

    return (
        <div
            className="relative flex flex-col space-x-2 nd-bg-lightgray p-2 rounded-xl"
            onKeyDown={handleKeyInput}
            ref={dropdownRef}
        >
            <div className="flex flex-row">
                <Image width={35} height={35} src={"/search.svg"} alt={"SEARCH ICON"} />
                <input
                    type="text"
                    placeholder="Search a station"
                    onChange={(e) => handleInputChange(e.target.value)}
                    className="nd-bg-lightgray text-2xl p-1 w-full focus:outline-none"
                    value={inputValue}
                    onFocus={() => setIsOpen(true)}
                />
            </div>
            {isOpen && query.length > 0 && (
                <div className="absolute top-full left-0 z-50 flex flex-col mt-2 nd-bg-lightgray rounded">
                    {query.map((location: Station, index) => (
                        <p
                            key={location.evaNr}
                            className={`m-1 text-white py-0.5 px-2 cursor-pointer nd-bg-lightgray hover:bg-gray-700 rounded ${
                                focusedQuery === index ? "bg-gray-700" : ""
                            }`}
                            onClick={() => selectStation(location)}
                            tabIndex={0}
                            role="button"
                            aria-pressed={focusedQuery === index}
                        >
                            {location.name}
                        </p>
                    ))}
                </div>
            )}
        </div>
    );
};

export default StationSearch;
